# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46880aac48bfd840f719b6750e3d9894294e207979aff27313b738f4e4b5d5b19e49e374fc421a097f13887f88af8e6ee9ca053d03792d9fe85a5073c4246b9b

test:
  secret_key_base: 8113508fd281f46cab7ac110ed8ccfdf19f5ca130fa870b1de1ffebf4ca4acfb2eaf847c35f0326810e4ac6470a847431ab8869d731cff357e59a3415654a549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
